name: 'Generate UUID'
description: 'Generates a UUID using the uuid module in python'
branding:
  icon: 
  color: 
runs:
  using: "composite"
  steps:
    - name: Update pip
      run: python3 -m pip install --upgrade pip
      shell: bash

    - name: install scratchattach
      run: pip install -U scratchattach
      shell: bash
