name: 'Generate UUID'
description: 'Generates a UUID using the uuid module in python'
branding:
  icon: archive
  color: red
inputs:
  version:
    description: 'Version of UUID to use'
    required: true
    default: 4
  namespace:
    description: "The UUID's namespace. Only applies to UUID versions 3 and 5."
    required: false
  name:
    description: "Name to use to create a UUID. Only applies to UUID versions 3 and 5."
    required: false
outputs:
  uuid:
    description: "The generated UUID"
    value: ${{ steps.generate.outputs.uuid }}
  safe:
    description: "The safeness of the UUID"
    value: ${{ steps.generate.outputs.safe }}
runs:
  using: "composite"
  steps:
    - name: Push local vars to env
      run: |
        echo "INPUT_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "INPUT_NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV
        echo "INPUT_NAME=${{ inputs.name }}" >> $GITHUB_ENV
      shell: bash

    - name: Generate UUID
      id: generate
      run: |
        pip install --upgrade pip
        python3 generate.py
      shell: bash
